version: '3.3'

services:
  postgres:
    restart: always
    build:
      context: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - 127.0.0.1:5432:5432

  django:
    restart: always
    build:
      context: ../
      dockerfile: docker/django/Dockerfile
    volumes:
      - settings:/src/mysite/settings_local/
      - static:/src/static/
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 127.0.0.1:9001:9000

  nginx:
    restart: always
    build:
      context: nginx
    volumes:
      - static:/src/static/
    depends_on: 
      - django
    links:
      - django
    ports:
      - 80:80

volumes:
  db_data: {}
  settings: {}
  static: {}
